# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1159, 660)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(520, 130, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(450, 260, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(450, 320, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(460, 460, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 139, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 183, 184);\n"
"    border-color: rgb(255, 130, 132);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 174, 175); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 110, 112); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 460, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 139, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 183, 184);\n"
"    border-color: rgb(255, 130, 132);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 174, 175); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 110, 112); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(540, 270, 151, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background: transparent; /* 设置背景为透明 */\n"
"    border: 2px solid rgb(255, 130, 132); /* 设置边框为粉色并且厚度为2px */\n"
"    border-radius: 15px; /* 设置圆角半径，这里假设输入框高度为30px */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(540, 330, 151, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background: transparent; /* 设置背景为透明 */\n"
"    border: 2px solid rgb(255, 130, 132); /* 设置边框为粉色并且厚度为2px */\n"
"    border-radius: 15px; /* 设置圆角半径，这里假设输入框高度为30px */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.login_) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "登录"))
        self.label_2.setText(_translate("Dialog", "用户名："))
        self.label_3.setText(_translate("Dialog", "密码："))
        self.pushButton.setText(_translate("Dialog", "进入"))
        self.pushButton_2.setText(_translate("Dialog", "退出"))
