# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maind.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1115, 697)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Dialog.setFont(font)
        Dialog.setMouseTracking(False)
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(250, 110, 621, 151))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(400, 460, 121, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 139, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 183, 184);\n"
"    border-color: rgb(255, 130, 132);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 174, 175); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 110, 112); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 460, 121, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 139, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 183, 184);\n"
"    border-color: rgb(255, 130, 132);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 174, 175); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 110, 112); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 520, 121, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 139, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 183, 184);\n"
"    border-color: rgb(255, 130, 132);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 174, 175); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 110, 112); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 520, 121, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 139, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 183, 184);\n"
"    border-color: rgb(255, 130, 132);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 174, 175); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 110, 112); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(370, 440, 371, 161))
        self.label.setStyleSheet("QLabel {\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    border-color: rgb(255, 205, 208);\n"
"    \n"
"     border-radius: 25px;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 139, 134, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 183, 184);\n"
"    border-color: rgb(255, 130, 132);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 174, 175); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 110, 112); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label.raise_()
        self.label2.raise_()
        self.pushButton.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_5.raise_()

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.goin) # type: ignore
        self.pushButton_2.clicked.connect(Dialog.goin2) # type: ignore
        self.pushButton_3.clicked.connect(Dialog.goin3) # type: ignore
        self.pushButton_4.clicked.connect(Dialog.close) # type: ignore
        self.pushButton_5.clicked.connect(Dialog.goback) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label2.setText(_translate("Dialog", "欢迎进入A路口交通监控系统"))
        self.pushButton.setText(_translate("Dialog", "进入监控"))
        self.pushButton_4.setText(_translate("Dialog", "退出系统"))
        self.pushButton_2.setText(_translate("Dialog", "车流量检测"))
        self.pushButton_3.setText(_translate("Dialog", "人流量检测"))
        self.pushButton_5.setText(_translate("Dialog", "返回登录"))
