# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitorf.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1125, 680)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 0, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 110, 811, 431))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(970, 600, 121, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 150, 145, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 2px solid rgb(255, 170, 172);\n"
"    border-color: rgb(255, 120, 122);\n"
"    border-radius: 20px; /* 设置圆角半径，数值可根据按钮大小调整 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 164, 165); /* 设置鼠标悬停时的背景颜色 */\n"
"    border: 2px solid rgb(255, 100, 102); /* 设置鼠标悬停时的边框颜色 */\n"
"    color: black; /* 设置鼠标悬停时的文本颜色 */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3); /* 设置鼠标悬停时的阴影效果 */\n"
"    cursor: pointer; /* 设置鼠标悬停时的指针样式 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(-10, -10, 1141, 691))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.fanhui) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "A路口监控区域"))
        self.pushButton.setText(_translate("Dialog", "返回上一级"))
